name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: list
        run: ls -a
      - name: change permission
        run: chmod +x configure
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: c compiler
        run: gcc code.c -o outputfile.exe
      - name: cd
        run: ls -a
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Changed files
